services:
  - type: web
    name: classplay
    runtime: static
    buildCommand: yarn build
    staticPublishPath: ./
    previews:
      generation: automatic
    buildFilter:
      paths:
      - /
